### ISSUE TITLE
Create individual rooms on Join

### ISSUE THREAD

**Issue by adityathakurxd** [adityathakurxd/make-real-polls#13]
Currently, everyone joins one big public room. It would be better if the users join a new room with a random ID, that they can invite other people to it using the room code.

- [x] Create a new room on join [using Rooms API](https://www.100ms.live/docs/server-side/v2/api-reference/Rooms/create-via-api)
- [x] Modify the demo yjs server to connect based on room
- [x] Add an option to accept room code and join a particular room invite

**Comment by KaustubhKumar05** [comment]
Suggestions:
- Store the roomCode in localStorage to avoid creating new rooms for the same peer. Additionally helps preserve the whiteboard state
- Support for roomCode query param, which can be used to set/override the localStorage value. If the query param is present, the Teacher/Student tabs can be hidden
